Update PluginRunner
UST-QuAntiL/tosca-definitions-quantil pull request #11
Opened 2022-06-03 10:54 UTC by mar-be

Changes:
- New Python Script Artifacts 
- Use a DA instead of cloning the PluginRunner from GitHub

2022-06-03 13:37 UTC, lharzenetter requested changes
Im currently running the deployment. However, some comments:

2022-06-03 13:37 UTC, lharzenetter commented on artifacttemplates/https%3A%2F%2Fust-quantil.github.io%2Fartifacttemplates/QHana-Plugin-Runner-Python_start-w1-wip1/ArtifactTemplate.tosca
> +    <ArtifactTemplate xmlns:otatyIgeneral="http://opentosca.org/artifacttypes" name="QHana-Plugin-Runner-Python_start-w1-wip1" type="otatyIgeneral:PythonScriptArtifact" id="QHana-Plugin-Runner-Python
Please also release this definition.

2022-06-03 13:37 UTC, lharzenetter commented on artifacttemplates/https%3A%2F%2Fust-quantil.github.io%2Fartifacttemplates/QHana-PluginRunner-Src-DA_w1-wip1/ArtifactTemplate.tosca
> +    <ArtifactTemplate xmlns:ToscaBaseTypes="http://docs.oasis-open.org/tosca/ns/2011/12/ToscaBaseTypes" name="QHana-PluginRunner-Src-DA_w1-wip1" type="ToscaBaseTypes:ArchiveArtifact" id="QHana-Plugin
s.a.

2022-06-03 13:37 UTC, lharzenetter commented on nodetypeimplementations/https%3A%2F%2Fust-quantil.github.io%2Fnodetypeimplementations/QHAna-PluginRunner-Implementation_latest-w2-wip1/LICENSE
> +   Copyright 2021 University of Stuttgart
I guess the year is 2022.

2022-06-03 13:37 UTC, lharzenetter commented on nodetypeimplementations/https%3A%2F%2Fust-quantil.github.io%2Fnodetypeimplementations/QHAna-PluginRunner-Implementation_latest-w2-wip1/NodeTypeImplementation.tosca
> +    <NodeTypeImplementation xmlns:nodeTypesQuantil="https://ust-quantil.github.io/nodetypes" targetNamespace="https://ust-quantil.github.io/nodetypeimplementations" name="QHAna-PluginRunner-Implement
s.a.

However, release this as the last element as you need to update the references to the IA/DAs.

2022-06-03 13:37 UTC, lharzenetter commented on nodetypes/https%3A%2F%2Fust-quantil.github.io%2Fnodetypes/QHAna-PluginRunner_latest-w2-wip1/LICENSE
> +   Copyright 2021 University of Stuttgart
2022.

2022-06-03 13:37 UTC, lharzenetter commented on nodetypes/https%3A%2F%2Fust-quantil.github.io%2Fnodetypes/QHAna-PluginRunner_latest-w2-wip1/NodeType.tosca
> +    <NodeType name="QHAna-PluginRunner_latest-w2-wip1" abstract="no" final="yes" targetNamespace="https://ust-quantil.github.io/nodetypes">
s.a.

2022-06-03 13:37 UTC, lharzenetter commented on nodetypes/https%3A%2F%2Fust-quantil.github.io%2Fnodetypes/QHAna-PluginRunner_latest-w2-wip1/README.md
> +- `MinWorkers. Minimum number of workers for the plugin runner
There is a backtick missing.

2022-06-03 13:37 UTC, lharzenetter commented on nodetypes/https%3A%2F%2Fust-quantil.github.io%2Fnodetypes/QHAna-PluginRunner_latest-w2-wip1/README.md
> +- `MaxWorkers. Maximum number of workers for the plugin runner
There is a backtick missing.

2022-06-03 13:37 UTC, lharzenetter commented on nodetypes/https%3A%2F%2Fust-quantil.github.io%2Fnodetypes/QHAna-PluginRunner_latest-w2-wip1/appearance/bigIcon.png.mimetype
> +image/png
The image is quite large. can you create a smaller version with max. 100x100px?

2022-06-10 12:44 UTC, lharzenetter approved these changes
Please check again, if the CORS issues are really gone before merging. Otherwise add the notice again.

2022-07-21 15:15 UTC, mar-be commented
> Please check again, if the CORS issues are really gone before merging. Otherwise add the notice again.

CORS issues are resolved: https://github.com/UST-QuAntiL/tosca-definitions-qc-applications/pull/12/commits/c67a3ad956e1f9b27d33d725f633732253c58b04

2022-07-21 15:17 UTC, mar-be commented
> Please check again, if the CORS issues are really gone before merging. Otherwise add the notice again.

https://github.com/UST-QuAntiL/tosca-definitions-qc-applications/pull/12 resolves the CORS issues

2022-07-22 05:22 UTC, lharzenetter approved these changes

2022-08-11 13:01 UTC, mar-be commented
Depends on https://github.com/OpenTOSCA/tosca-definitions-common/pull/36

2022-08-12 08:10 UTC, merged