Add node types to deploy PlanQK services
UST-QuAntiL/tosca-definitions-quantil pull request #15
Opened 2022-12-13 10:29 UTC by PhilWun

This PR adds new node types that can deploy services on the PlanQK platform.

New node types:
  * PlanQK-Platform
  * PlanQK-Service
  * PlanQK-ServiceInstanceInfo

2022-12-13 12:14 UTC, lharzenetter requested changes
There are some things left to do:
- [ ] Release all definitions
- [ ] Move the example to the [qc applications](https://github.com/UST-QuAntiL/tosca-definitions-qc-applications)
- [ ] Try to get rid of the `ServiceInfo` type
- [ ] Clean up the `Namespaces.json` afterwards
- [ ] Everything within the generated target folder must be ignored. Remove all files and then add it to the ignore list using `**/*/target`

2022-12-13 12:14 UTC, lharzenetter commented on servicetemplates/http%3A%2F%2Fopentosca.org%2Fservicetemplates/PlanQK-Service-Example_w1-wip1/ServiceTemplate.tosca
> +    <ServiceTemplate name="PlanQK-Service-Example_w1-wip1" targetNamespace="http://opentosca.org/servicetemplates" id="PlanQK-Service-Example_w1-wip1">
This should be in the [qc applications](https://github.com/UST-QuAntiL/tosca-definitions-qc-applications) repository

2022-12-13 12:14 UTC, lharzenetter commented on nodetypes/https%3A%2F%2Fust-quantil.github.io%2Fnodetypes/PlanQK-Service_w1-wip1/README.md
> +The DA with the user code needs to be an ArchiveArtifact and the file name needs to be `user_code.zip`.
Why does it have to be `user_code.zip`?

2022-12-13 12:14 UTC, lharzenetter commented on nodetypes/https%3A%2F%2Fust-quantil.github.io%2Fnodetypes/PlanQK-Service_w1-wip1/README.md
> +Adding it to the Node Type Implementation **does NOT work**.
Shortly explain why so that users can understand the difference.

2022-12-13 12:14 UTC, lharzenetter commented on nodetypes/https%3A%2F%2Fust-quantil.github.io%2Fnodetypes/PlanQK-Service_w1-wip1/NodeType.tosca
> +    <NodeType name="PlanQK-Service_w1-wip1" abstract="no" final="no" targetNamespace="https://ust-quantil.github.io/nodetypes" winery:bordercolor="#0c00ff">
Please release the Node Type and make the color `3e8ccd` (the color of the icon :))

2022-12-13 12:14 UTC, lharzenetter commented on nodetypes/https%3A%2F%2Fust-quantil.github.io%2Fnodetypes/PlanQK-ServiceInstanceInfo_w1-wip1/README.md
> +- `ServiceID`: don't set a values for this property. It will be automatically set when the service is deployed.
In written English, avoid don't and use do not. Please use `a value`.

2022-12-13 12:14 UTC, lharzenetter commented on nodetypes/https%3A%2F%2Fust-quantil.github.io%2Fnodetypes/PlanQK-ServiceInstanceInfo_w1-wip1/NodeType.tosca
> +    <NodeType name="PlanQK-ServiceInstanceInfo_w1-wip1" abstract="no" final="no" targetNamespace="https://ust-quantil.github.io/nodetypes" winery:bordercolor="#fc00ff">
I still think we can get rid of this...

2022-12-13 12:14 UTC, lharzenetter commented on nodetypes/https%3A%2F%2Fust-quantil.github.io%2Fnodetypes/PlanQK-Platform_w1-wip1/README.md
> +- `PlanQKApiKey`: personal access token for the PlanQK platform. Should be set to `get_input: PlanqkApiKey`.
Set `get_input: PlanqkApiKey` as the default value in the properties definition.

2022-12-13 12:14 UTC, lharzenetter commented on artifacttemplates/https%3A%2F%2Fust-quantil.github.io%2Fartifacttemplates/PlanQK-Service-IA_w1-wip1/source/README.md
> +* Java Package: org.opentosca.nodetypes
I guess in this case we could use `org.ust.quantil.nodetypes`

2022-12-13 12:14 UTC, lharzenetter commented on artifacttemplates/https%3A%2F%2Fust-quantil.github.io%2Fartifacttemplates/PlanQK-Service-IA_w1-wip1/source/LICENSE
> +   Copyright 2021 University of Stuttgart
We have 2022 :)

2022-12-14 09:01 UTC, PhilWun commented on nodetypes/https%3A%2F%2Fust-quantil.github.io%2Fnodetypes/PlanQK-Service_w1-wip1/README.md
> +The DA with the user code needs to be an ArchiveArtifact and the file name needs to be `user_code.zip`.
The `create` operation gets the DAs as a dictionary with the file names as keys and the URLs as values. To get the right DA I let it search for a DA with this specific file name.

2023-01-13 08:32 UTC, lharzenetter requested changes

2023-01-13 08:32 UTC, lharzenetter commented on artifacttemplates/https%3A%2F%2Fust-quantil.github.io%2Fartifacttemplates/PlanQK-Platform-IA_w1/LICENSE
> +   Copyright [yyyy] [name of copyright owner]
Please add 2023 University of Stuttgart

2023-01-13 08:32 UTC, lharzenetter commented on artifacttemplates/https%3A%2F%2Fust-quantil.github.io%2Fartifacttemplates/PlanQK-Platform-IA_w1/PlanQK-Platform__ContainerInterface.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Add `*.iml` files to the git ignore list and remove this file

2023-01-13 08:32 UTC, lharzenetter commented on artifacttemplates/https%3A%2F%2Fust-quantil.github.io%2Fartifacttemplates/PlanQK-Platform-IA_w1/source/README.md
> +# Generated Implementation Artifact Skeleton for io_github_ust_quantil_artifacttemplates_PlanQKPlatform__ContainerManagementInterface
Please update this readme to conform to the current workflow.

2023-01-13 08:32 UTC, lharzenetter commented on artifacttemplates/https%3A%2F%2Fust-quantil.github.io%2Fartifacttemplates/PlanQK-Service-User-Code_-DA-w1/LICENSE
> +   Copyright [yyyy] [name of copyright owner]
See above.

2023-01-13 08:32 UTC, lharzenetter commented on nodetypeimplementations/https%3A%2F%2Fust-quantil.github.io%2Fnodetypeimplementations/PlanQK-Platform-Implementation_w1/LICENSE
> +   Copyright [yyyy] [name of copyright owner]
See above

2023-01-13 08:32 UTC, lharzenetter commented on nodetypes/https%3A%2F%2Fust-quantil.github.io%2Fnodetypes/PlanQK-Platform_w1/LICENSE
> +   Copyright [yyyy] [name of copyright owner]
See above

2023-01-13 08:32 UTC, lharzenetter commented on nodetypes/https%3A%2F%2Fust-quantil.github.io%2Fnodetypes/PlanQK-Service_w1/LICENSE
> +   Copyright [yyyy] [name of copyright owner]
See above

2023-01-16 11:38 UTC, lharzenetter approved these changes

2023-01-16 11:41 UTC, merged